import { cookies } from 'next/headers';
import { createHmac, randomBytes, scryptSync, timingSafeEqual } from 'node:crypto';

/**
 * Minimal shared-secret admin gate.
 *
 * Deliberately not a user system: the MVP has one operator. The cookie carries a
 * signed, expiring token rather than the password itself.
 *
 * The password may be supplied two ways:
 *   ADMIN_PASSWORD_HASH  preferred - `scrypt$<salt hex>$<hash hex>`, generated by
 *                        `npm run admin:hash`. The plaintext never reaches the
 *                        server, so a leaked environment does not leak a
 *                        reusable password.
 *   ADMIN_PASSWORD       fallback for local development.
 */

export const ADMIN_COOKIE = 'cr_admin';
const TTL_MS = 12 * 3600_000;
const SCRYPT_KEYLEN = 32;

function passwordHash() {
  return process.env.ADMIN_PASSWORD_HASH || '';
}

function plainPassword() {
  return process.env.ADMIN_PASSWORD || '';
}

/**
 * Key for signing the session cookie.
 *
 * Derived from whichever credential is configured, so the cookie secret is never
 * the password itself and rotating the password invalidates live sessions.
 */
function signingKey() {
  return passwordHash() || plainPassword();
}

function sign(expires: number) {
  return createHmac('sha256', signingKey()).update(`admin.${expires}`).digest('hex');
}

export function issueToken(): string {
  const expires = Date.now() + TTL_MS;
  return `${expires}.${sign(expires)}`;
}

export function verifyToken(token: string | undefined): boolean {
  if (!token || !signingKey()) return false;
  const [expiresRaw, sig] = token.split('.');
  const expires = Number(expiresRaw);
  if (!expires || !sig || expires < Date.now()) return false;
  return safeEqual(sig, sign(expires));
}

function safeEqual(a: string, b: string): boolean {
  const bufA = Buffer.from(a, 'utf8');
  const bufB = Buffer.from(b, 'utf8');
  return bufA.length === bufB.length && timingSafeEqual(bufA, bufB);
}

/** `scrypt$<salt>$<hash>` — the format `npm run admin:hash` emits. */
export function hashPassword(password: string): string {
  const salt = randomBytes(16);
  const hash = scryptSync(password, salt, SCRYPT_KEYLEN);
  return `scrypt$${salt.toString('hex')}$${hash.toString('hex')}`;
}

export function checkPassword(candidate: string): boolean {
  const stored = passwordHash();

  if (stored) {
    const [scheme, saltHex, hashHex] = stored.split('$');
    if (scheme !== 'scrypt' || !saltHex || !hashHex) return false;
    let derived: Buffer;
    try {
      derived = scryptSync(candidate, Buffer.from(saltHex, 'hex'), SCRYPT_KEYLEN);
    } catch {
      return false;
    }
    const expected = Buffer.from(hashHex, 'hex');
    return derived.length === expected.length && timingSafeEqual(derived, expected);
  }

  const configured = plainPassword();
  if (!configured) return false;
  return safeEqual(candidate, configured);
}

export async function isAdmin(): Promise<boolean> {
  const jar = await cookies();
  return verifyToken(jar.get(ADMIN_COOKIE)?.value);
}

export function adminConfigured(): boolean {
  return Boolean(signingKey());
}
