/**
 * Applies the canonical schema to DATABASE_URL and mirrors it to db/schema.sql
 * for anyone who prefers pasting into the Supabase SQL editor.
 */
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { SCHEMA_SQL } from '../lib/db/schema-sql';

async function main() {
  const outPath = path.join(process.cwd(), 'db', 'schema.sql');
  await fs.mkdir(path.dirname(outPath), { recursive: true });
  await fs.writeFile(outPath, `-- Generated by \`npm run db:push\`. Edit lib/db/schema-sql.ts instead.\n${SCHEMA_SQL}`);
  console.log(`Wrote ${path.relative(process.cwd(), outPath)}`);

  if (!process.env.DATABASE_URL) {
    console.log('DATABASE_URL not set - schema written but not applied.');
    return;
  }
  const { createPostgresStore } = await import('../lib/db/postgres-store');
  await createPostgresStore().migrate();
  console.log('Schema applied to DATABASE_URL.');
  process.exit(0);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
